/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PerroImport } from './routes/perro'
import { Route as ContacUsImport } from './routes/contacUs'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PerroRoute = PerroImport.update({
  id: '/perro',
  path: '/perro',
  getParentRoute: () => rootRoute,
} as any)

const ContacUsRoute = ContacUsImport.update({
  id: '/contacUs',
  path: '/contacUs',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/contacUs': {
      id: '/contacUs'
      path: '/contacUs'
      fullPath: '/contacUs'
      preLoaderRoute: typeof ContacUsImport
      parentRoute: typeof rootRoute
    }
    '/perro': {
      id: '/perro'
      path: '/perro'
      fullPath: '/perro'
      preLoaderRoute: typeof PerroImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacUs': typeof ContacUsRoute
  '/perro': typeof PerroRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacUs': typeof ContacUsRoute
  '/perro': typeof PerroRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacUs': typeof ContacUsRoute
  '/perro': typeof PerroRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/contacUs' | '/perro'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/contacUs' | '/perro'
  id: '__root__' | '/' | '/about' | '/contacUs' | '/perro'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContacUsRoute: typeof ContacUsRoute
  PerroRoute: typeof PerroRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContacUsRoute: ContacUsRoute,
  PerroRoute: PerroRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/contacUs",
        "/perro"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/contacUs": {
      "filePath": "contacUs.tsx"
    },
    "/perro": {
      "filePath": "perro.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
